Repository SparkDevNetwork/Rock, pull requests merged in 2019-10, with the labels that each got.

#3955 Fixed exception in BusinessList block when a business had no address
  RockWeb/Blocks/Finance/BusinessList.ascx.cs
Labels: PR Ready

#3962 - Fixed extra spaces in names and incorrect param/code comments (Fixes 2554)
  database/Functions/ufnCrm_GetFamilyTitle.sql
  database/Functions/ufnCrm_GetFamilyTitleIncludeInactive.sql
Labels: PR Code Reviewed, PR QA Tested, PR Ready

#3759 Corrected Issue with Data Automation settings for Interactions not saving
  RockWeb/Blocks/Administration/DataAutomationSettings.ascx.cs
Labels: PR QA Tested, PR Ready

#3956 + Updated the RestKeyList block to show inactive REST users
  RockWeb/Blocks/Security/RestKeyList.ascx
  RockWeb/Blocks/Security/RestKeyList.ascx.cs
Labels: PR Ready

#3417 Unsubscribe link should give specific list options
  RockWeb/Blocks/Communication/EmailPreferenceEntry.ascx.cs
Labels: PR Code Reviewed, PR QA Tested, PR Ready

#3655 Fixed content channel item ordering. Fixes #2522
  RockWeb/Blocks/Cms/ContentChannelItemDetail.ascx
  RockWeb/Blocks/Cms/ContentChannelItemDetail.ascx.cs
Labels: PR Code Reviewed, PR QA Tested, PR Ready

#3969 Fixes #3963 Transfer only if there are other opportunities
  RockWeb/Blocks/Connection/ConnectionRequestDetail.ascx.cs
Labels: PR Code Reviewed, PR QA Tested, PR Ready

#3970 - Fixed blank instruction page in Event Registration. (Fixes #3937)
  RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
Labels: PR Code Reviewed, PR QA Tested
