Repository SparkDevNetwork/Rock, pull requests merged in 2019-11, with the labels that each got.

#3616 Fixes #3608. SendDigitialSignatureRequestTransaction
  Rock/Transactions/SendDigitalSignatureRequestTransaction.cs
Labels: PR Code Reviewed, PR QA Tested, PR Ready

#3978 Update name formatting in pledge analytics to match giving analytics
  RockWeb/Blocks/Finance/PledgeAnalytics.ascx.cs
Labels: PR Code Reviewed, PR QA Tested, PR Ready

#3977 Removed dataview filters related to archived group members
  Rock/Model/GroupMember.cs
Labels: PR Code Reviewed, PR QA Tested

#3987 - Fixed bug that prevented proper selection of all stored values if they were delimited by more than just a single comma
  Rock/Field/SelectFromListFieldType.cs
Labels: PR Code Reviewed, PR Ready

#3998 Fixed Lucene path mapping to work with virtual directories
  Rock/UniversalSearch/IndexComponents/Lucene.cs
Labels: PR Code Reviewed, PR Ready

#4001 Fixed campus order not being cached in Redis
  Rock/Web/Cache/Entities/CampusCache.cs
Labels: PR Code Reviewed, PR Ready

#3929 Improved location detail block. Fixes #3657
  RockWeb/Blocks/Core/LocationDetail.ascx.cs
Labels: PR Code Reviewed, PR QA Tested, PR Ready
