Repository SparkDevNetwork/Rock, pull requests merged in 2020-01, with the labels that each got.

#4050 Fixed null reference check
  RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
Labels: PR Ready

#4052 + Added the ability to see and edit values for entity attributes on the site detail block
  RockWeb/Blocks/Cms/SiteDetail.ascx
  RockWeb/Blocks/Cms/SiteDetail.ascx.cs
Labels: PR Code Reviewed, PR QA Tested, PR Ready

#4064 Fixed incorrect pending member count in the "Group Leader Pending Notifications" job's status message.
  Rock/Jobs/GroupLeaderPendingNotifications.cs
Labels: PR Code Reviewed, PR Ready

#4069 - Fixed an null reference exception when attempting to load a page by…
  Rock/Web/RockRouteHandler.cs
Labels: PR Code Reviewed, PR QA Tested

#4074 Fixed issue where workflow outruns system clock
  RockWeb/Blocks/WorkFlow/WorkflowEntry.ascx.cs
Labels: PR Code Reviewed, PR Ready

#4080 Added channel Id context to get component function of Interaction Add workflow action
  Rock/Workflow/Action/Utility/InteractionAdd.cs
Labels: PR Code Reviewed, PR Ready

#4082 - Fixed auto-complete text to no longer be same color as background.
  RockWeb/Styles/_rock-variables.less
Labels: PR Code Reviewed, PR Ready

#4029 Workflow.Action.Utility.SetEntityProperty: Set Nullable Enum
  Rock/Workflow/Action/Utility/SetEntityProperty.cs
Labels: PR Code Reviewed, PR QA Tested, PR Ready

#4019 - Fixed bug that forced the OnRowSelectedEnabled property of the RockTemplateField to always be true.
  Rock/Web/UI/Controls/Grid/RockTemplateField.cs
Labels: PR Code Reviewed, PR QA Tested, PR Ready
