Repository SparkDevNetwork/Rock, pull requests merged in 2020-02, with the labels that each got.

#4071 Fixed bug where inline legal forms would cause errors with waitlists
  RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
Labels: PR Ready

#4072 Added lava regex with multiple matches
  Rock.Tests/Rock/Lava/RockFiltersTests.cs
  Rock/Lava/RockFilters.cs
Labels: PR Code Reviewed, PR QA Tested, PR Ready

#4073 Add public cacheability header when the file type is marked as cacheable
  RockWeb/App_Code/GetImage.ashx.cs
Labels: PR Code Reviewed, PR QA Tested, PR Ready

#4095 Added the ability to view and edit custom attribute values for metric entity on the metric detail block
  RockWeb/Blocks/Reporting/MetricDetail.ascx
  RockWeb/Blocks/Reporting/MetricDetail.ascx.cs
Labels: PR Code Reviewed, PR QA Tested, PR Ready

#4098 Fixed bug with pickers and collision of Id numbers
  Rock/Web/UI/Controls/Pickers/CategoryPicker.cs
  Rock/Web/UI/Controls/Pickers/ItemPicker.cs
  RockWeb/Scripts/Rock/Controls/itemPicker.js
  RockWeb/Scripts/Rock/Extensions/rockTree.js
Labels: PR Code Reviewed, PR Ready

#4107 Fix "Invalid Body" warning from Twilio when no response is returned from the webhook
  RockWeb/Webhooks/TextToWorkflowTwilio.ashx
  RockWeb/Webhooks/Twilio.ashx
  RockWeb/Webhooks/TwilioSms.ashx
Labels: PR Code Reviewed, PR Ready

#4103 + Added new Allow Donations Until date on fundraising opportunities. (Fixes #3438)
  Rock.Migrations/Migrations/202002111831294_AddFundraisingAllowDonationsUntil.cs
  RockWeb/Blocks/Fundraising/FundraisingDonationEntry.ascx.cs
  RockWeb/Blocks/Fundraising/FundraisingOpportunityView.ascx.cs
Labels: PR Code Reviewed, PR Ready

#4096 + Added new EntityFromCacheObject Lava filter. (Fixes #4089)
  Rock.Tests/Rock.Tests.csproj
  Rock.Tests/Rock/Utility/ExtensionMethods/TypeExtensionsTests.cs
  Rock/Lava/RockFilters.cs
  Rock/Rock.csproj
  Rock/Utility/ExtensionMethods/TypeExtensions.cs
Labels: PR Code Reviewed, PR Ready

#4117 + Fixed issue where urls were generated with http even though site is loaded over https.
  Rock/Web/UI/RockPage.cs
Labels: PR Code Reviewed, PR Ready

#4140 Prevent double postback for radio buttons
  RockWeb/Scripts/Rock/Controls/fieldVisibilityWrapper.js
Labels: PR Code Reviewed, PR Ready

#4128 + Improved performance of Orphaned Attribute Cleanup. (Fixes #4127)
  Rock/Model/AttributeMatrixService.Partial.cs
Labels: PR Code Reviewed, PR QA Tested
