Repository SparkDevNetwork/Rock, pull requests merged in 2021-01, with the labels that each got.

#4531 Validate username in AccountEntry block
  RockWeb/Blocks/Security/AccountEntry.ascx.cs
Labels: PR Code Reviewed, PR QA Tested

#4535 Fix incorrect graduation year on GradeTransitionDate
  Rock/Web/UI/Controls/Pickers/GradePicker.cs
Labels: PR Ready

#4565 + Fix inability to remove fees during registration (Fixes #4558)
  RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
Labels: PR Code Reviewed

#4554 Update Twilio webhooks to avoid "Invalid Body" warnings from Twilio
  RockWeb/Webhooks/Twilio.ashx
  RockWeb/Webhooks/TwilioSms.ashx
Labels: PR Ready
